# This file was generated by GoReleaser. DO NOT EDIT.
cask "mfa" do
  version "1.1.1"

  on_macos do
    on_intel do
      sha256 "9251d8b2b141e83a4fa7de06b5a040ad9793b237d4e39a6d2bcbc95dcb67a498"
      url "https://github.com/LexSerest/mfa/releases/download/v#{version}/mfa_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "4a4e4b71543a9a2c977d344b814d64e1bf6d1a319b2adf44985d6c45a9c271bf"
      url "https://github.com/LexSerest/mfa/releases/download/v#{version}/mfa_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "bef1ddc827c987add38abfd6a4f157228140f06b65ce07eaad1f8f5f1468ccd7"
      url "https://github.com/LexSerest/mfa/releases/download/v#{version}/mfa_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "3877f797a5c03e0aedd8f562b0890c360f29fdde2f9874b8e526d1fa888d653f"
      url "https://github.com/LexSerest/mfa/releases/download/v#{version}/mfa_#{version}_linux_arm64.tar.gz"
    end
  end

  name "mfa"
  desc "Secure 2FA CLI manager"
  homepage "https://github.com/LexSerest/mfa"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mfa"
  bash_completion "completions/mfa.bash"
  fish_completion "completions/mfa.fish"
  zsh_completion "completions/mfa.zsh"

  # No zap stanza required

end
