# This file was generated by GoReleaser. DO NOT EDIT.
cask "mfa" do
  version "1.1.0"

  on_macos do
    on_intel do
      sha256 "0ec26878ec16114477c57e21ced86691506a2d94700508b6105b2c6c6a3cd67d"
      url "https://github.com/LexSerest/mfa/releases/download/v#{version}/mfa_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "65155cd8000d0b7da2878e20f88fe0d2c001315751cf54287affcdc023e5b341"
      url "https://github.com/LexSerest/mfa/releases/download/v#{version}/mfa_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "a35045f6d35edd7e1efce86c7096a8c090876254ca27e6b39cb3588527a8fb80"
      url "https://github.com/LexSerest/mfa/releases/download/v#{version}/mfa_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "83a919061e029c95469faaf757e7ce7ea8eec6fda58652ada1ddcd4ad01b93dd"
      url "https://github.com/LexSerest/mfa/releases/download/v#{version}/mfa_#{version}_linux_arm64.tar.gz"
    end
  end

  name "mfa"
  desc "Secure 2FA CLI manager"
  homepage "https://github.com/LexSerest/mfa"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mfa"
  bash_completion "completions/mfa.bash"
  fish_completion "completions/mfa.fish"
  zsh_completion "completions/mfa.zsh"

  # No zap stanza required

end
