# This file was generated by GoReleaser. DO NOT EDIT.
cask "mfa" do
  version "1.0.0"

  on_macos do
    on_intel do
      sha256 "a74cf797ecbcb5ac8509ea7c7fa233a715e856e9d9a36606d0baea1779df26f3"
      url "https://github.com/LexSerest/mfa/releases/download/v#{version}/mfa_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "e26d359c24e899a022183cc67a614e3be8109d43d4673bd12e83ed0c68e01a50"
      url "https://github.com/LexSerest/mfa/releases/download/v#{version}/mfa_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "dbdfceed0fd1259af82538287abd0487c8de5255ffe23fd18f1c277c3e73db28"
      url "https://github.com/LexSerest/mfa/releases/download/v#{version}/mfa_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "cff4ce915a1186cc57c3ffffda122660f175f2c0b5e9edd1c17fad1a298fa680"
      url "https://github.com/LexSerest/mfa/releases/download/v#{version}/mfa_#{version}_linux_arm64.tar.gz"
    end
  end

  name "mfa"
  desc "Secure 2FA CLI manager"
  homepage "https://github.com/LexSerest/mfa"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mfa"
  bash_completion "completions/mfa.bash"
  fish_completion "completions/mfa.fish"
  zsh_completion "completions/mfa.zsh"

  # No zap stanza required

end
